/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package jp.co.kelly.restapi;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import jp.co.kelly.restapi.dto.BooksDto;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-01-04T00:18:46.053657400+09:00[Asia/Tokyo]")

@Validated
@Api(value = "books", description = "the books API")
public interface BooksApi {

    @ApiOperation(value = "本を検索する", nickname = "booksGet", notes = "", response = BooksDto.class, tags={ "books", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BooksDto.class) })
    @RequestMapping(value = "/books",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<BooksDto> booksGet();

}
